### ISSUE TITLE
Fix f\nametag\include\f_nametagBrief.sqf

### ISSUE THREAD

**Issue by audiox** [Raptoer/F3#63] opened 2017-09-29 17:41 UTC
line 17 is wrong. Dunno how it should be, but there's a bracket missing and some stuff.

**Comment by audiox** [comment] 2017-09-29 17:56
17:54:55 c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
17:54:55 No speaker given for 
17:54:56 Weather was forced to change
17:55:16  Mission id: 8c37dbb0603eef4ba7d0a9785a479a7d4c73b99a
17:55:16 Error in expression <DON OPTIONS.
	",F_NT_ACTIONKEY_KEYNAME, F_NT_ACTIONKEY_KEY,F_NT_DRAWDISTANCE_NEA>
17:55:16   Error position: <F_NT_ACTIONKEY_KEY,F_NT_DRAWDISTANCE_NEA>
17:55:16   Error Undefined variable in expression: f_nt_actionkey_key
17:55:16 File C:\Users\Gerhard\Documents\Arma 3 - Other Profiles\audiox\mpmissions\f3-fa-v27Sep2017.Altis\f\nametag\include\f_nametagBrief.sqf, line 17
17:55:16 Empty word in sentence ''

**Comment by SamLex** [comment] 2017-09-29 21:28
This seems to be caused by the "Time acceleration" key being unbound in controls.

**Comment by SamLex** [comment] 2017-09-29 21:37
Fixed in PR #64

**Closed** 2017-10-01 05:37 UTC
Labels: Bug
