### ISSUE TITLE
Persistent Helicopter noise after mission end

### ISSUE THREAD

**Issue by ninjaProtocol** [Raptoer/F3#44] opened 2017-09-18 22:21 UTC
The infamous bug. F3 or BI bug?

**Comment by SamLex** [comment] 2017-09-19 07:20
Before we could even think about working out the cause, we would need a way to semi-reliably reproduce the bug. Which, last time I checked, no one has achieved

**Comment by SamLex** [comment] 2017-11-04 14:57
A potentially 'fix' for this, since we have mpEnd anyway, would be to destroy all player-occupied helicopters at mission's end. Would probably want to eject them and make them invincible first to avoid triggering other endings, but that is details.

**Comment by shadow-fa** [comment] 2017-12-27 02:45
Related ticket(s) in the BI feedback tracker:
- https://feedback.bistudio.com/T80726

**Comment by SamLex** [comment] 2018-01-09 00:03
Closing due to the issue not being observed recently (mainly do to hosting countermeasures) and it being a BI bug anyway

**Closed by SamLex** 2018-01-09 00:03 UTC
Labels: Bug, Bug (BI's fault), WontFix
